### PR TITLE
IKE-GW Floating IP Support

### PR DESCRIPTION
**Pull request by mandrewdx**
For Firewalls configured in an HA Active-Active scenario, using Floating IP's for the ike-gw

### CODE REVIEW

**Comment by shinmog** [comment]
@mandrewdx 

Thanks for this; my attention is currently diverted so it may be a week or two before I can look at this.

Few questions while you wait:

* Does this affect both Panorama and firewall, or just firewall?
* Seems there's no update to the unit tests with this PR; please add at least one test per version.
* Which versions of PAN-OS have you tested this with?

**Comment by mandrewdx** [comment]
No worries, we all have things to do. I added support to the tf provider and built locally to get me by until it’s in master. 
To answer your questions...
- I’m not entirely sure. I will check later today to see if Floating IPs are supported in config templates. My gut wants to say no, but I’ll confirm. 
- Will do
- 7.1 and 8.1 have been tested with at this time. Past that, im out of devices that will even support A-A. 

Let me know if you need anything else, happy to help/adjust any way I can.

**Comment by mandrewdx** [comment]
@shinmog Alright, I believe I've made all needed changes. A few points..
- Tracking down version support was a little tricky, the pan support website seems to have removed anything pre-7.1 from any of the docs. Unfortunately I didn't have any firewalls laying around/deployed that were < 7.1 either. However in the new features guide for 7.1 I did find the Floating IP feature being mentioned, and differences in the behavior in A/A configurations which appear to be necessary for Ike GW configurations to be supported in an A/A scenario. Without being able to 100% validate that floatingIP support will work on < 7.1, I felt it was best to split it out to not rock the boat. 
- All unit tests have been updated
- I've included some details about my thought processes when I was making all of the changes. If you don't agree with anything, let me know, I'm happy to update.
- Floating IP's do appear to be supported from Panorama. I've expanded support to that as well, and updated the unit tests accordingly

AWS announced that they'll be killing off all remaining Classic VPN's, which gave me a huge headache to deal with, so it gave me a little bit of a kick in the ass to get this done. Thanks for reviewing and let me know if you need anything else!

**Comment by mandrewdx** [comment]
Thanks @shinmog - Let me know if I need to do anything else to get this version into the terraform provider.

**Comment by shinmog** [comment]
@mandrewdx 

You don't.  I need to update the provider to support the new HCL v2, and that's a minor version bump.  I'm thinking I might be able to sneak this update in there since, Terraform side, it's not adding a new param or anything, just allowing an existing param to have a new value.  In any case, you don't need to do anything else now.

**Comment by shinmog** [comment]
@mandrewdx 

Just FYI, I'm updating the string value for `LocalTypeFloatingIp` from "floating" to "floating-ip"; so in Terraform it'll be "floating-ip" as well.

**Pull request merged**
