### PR TITLE
fixes #82 - add extras parameter to client.WaitForJob

### LINKED ISSUE #82: Extras parameter missing from client.WaitForJob
## Describe the bug

Error while using `client.WaitForJob` for a commit job which was issued to a connected device from Panorama. This happens only when the request doesn't have required `target` field present.

## Expected behavior

`client.WaitForJob` should accept `extras` parameter so that it can be passed to `client.Op` for setting proper request fields.

## Current behavior

`extras` parameter is missing from `client.WaitForJob` and `nil` is passed to underlying `client.Op` call.

https://github.com/PaloAltoNetworks/pango/blob/d1a0bc858db2fe531dd1d7a8a0fdb13212c24cd8/client.go#L519

## Possible solution

Add `extras` parameter in `client.WaitForJob` or keep it separate in a new function.

## Steps to reproduce

1. Connect to Panorama; do not set `client.Target`;
2. Issue a commit job to a connected device:
```go
extras := url.Values{"target": []string{"<device name>"}}
jobID, _, err := client.Commit(cmd, "", extras)
```
3. wait for the job to complete:
```go
err := client.WaitForJob(jobID, time.Duration(30)*time.Second, nil)
```

## Context

I am not setting `Target` field in the `pango.Client` itself because the target device is not fixed even during execution and hence I've to do this via `extras` parameter in other functions like `client.Get` or `client.Commit`. This `extras` parameter is missing from `client.WaitForJob`.

### PR DESCRIPTION
**Pull request by pangteypiyush**
## Description

add extras parameter to client.WaitForJob

## Motivation and Context

Fixes #82

## How Has This Been Tested?

Tested in Panorama 9.1.9 with connected PanOS 9.1.9 devices.

## Types of changes

- Breaking change

## Checklist

- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by shinmog** [comment]
Just FYI, last time I made a change that affected the commit script, multiple people who were getting pango from master instead of the latest tagged release complained it didn't work.  I'll merge this in a bit when I'm closer to tagging the next release.

**Review by shinmog — APPROVED** [review]
lgtm

**Comment by shinmog** [comment]
This PR needs a rebase before I can merge

**Comment by pangteypiyush** [comment]
Hi @shinmog, I have rebased the changes.

**Comment by shinmog** [comment]
Ah, you have to update the mockclient stuff under testdata

**Comment by shinmog** [comment]
Hrm, I guess I can do that.  Thanks for the work on this!

**Pull request merged**
